### ISSUE TITLE
Padding characters displaying variable names, not the symbols

### ISSUE THREAD

**Issue by polymachine** [Moarram/headline#11]
There seems to be some problem with variable parsing in my version of the Theme:
(zsh v 5.0.2) / CentOS 7.9.2009

![image](https://user-images.githubusercontent.com/34231430/149777916-491f05ed-7aed-4af8-8dc0-e5772b6ddf71.png)

also the function headline_git reports that error before every promt...

**Comment by Moarram** [comment]
The theme utilizes some syntax that must have been added in a newer version of Zsh. Is it possible for you to upgrade to a newer version? (5.0.6 at least)

**Comment by polymachine** [comment]
unfortunately no, since I'm not an admin on this machine.
I'm wondering why an update within 5.0.X would introduce new syntax, but I suppose that is not your decision to make ...

**Comment by Moarram** [comment]
In the [Zsh Release Notes](https://zsh.sourceforge.io/releases.html), the change from 5.0.5 to 5.0.6 includes the following:

> In prompt strings, the %N(l.true.false) conditional (line length) and the %N<..< and %N>..> truncation operators now accept negative values of N, which count the remaining space to the opposite margin (positive values of N still count the space used since the start of the prompt).

This caught my attention because the prompt uses this syntax. But it shouldn't matter because I don't use negative values for N, so that's probably not the issue.

**Comment by Moarram** [comment]
Still no idea on the `headline_git_status:2: unknown file attribute` error. The line in question is an array assignment of the form `local array=('A' 'B' 'C')`, which seems innocent enough.

All the other oddities have in common a particular syntax of string substitution. The syntax `"${(pl:$n::$char:)}"` produces a string of `$char` repeated `$n` times. This is used for the line above the prompt and the padding between the path and git info. Perhaps you have some Zsh setting that's interfering with this substitution? I may unknowingly rely on a default setting.

**Comment by Moarram** [comment]
@polymachine I finally got around to setting up a CentOS virtual machine with Zsh 5.0.2 and replicated the issue. It turns out that in older versions of Zsh you couldn't declare and assign a local array at the same time, and that the p flag in the string substitution wasn't yet a feature. I've worked around these limitations (albeit with more lines of code) so now Headline is compatible with Zsh 5.0.2

**Comment by polymachine** [comment]
Thanks! The symbols work now, although Konsole seems to refuse to use Fire Code's ligaturesn (that's not your problem tho). Unfortunately the headline_git_status thing has not diasappeared, only changed: `headline_git_status:19: number expected`...
I am at this point fully willing not to further torment you with backwards compatibility issues and restrain myself to just using headline on my personal PC
