### ISSUE TITLE
Ligatures not working correctly

### ISSUE THREAD

**Issue by iCraft85** [Moarram/headline#12]
So I just started using Victor Mono from the Nerd Fonts and was trying to use headline but the bar doesn't seem to wanna show up properly

<img width="400" alt="Screenshot 2022-05-08 at 4 56 36 PM" src="https://user-images.githubusercontent.com/58494292/167289079-239b66c7-c990-403c-89fd-2a9048e199b7.png">

As you can see in the screen shot some of the line seems to function whilst the majority doesn't want to work

I am running MacOS Big Sur with kitty terminal 
These are the settings for my fonts:
<img width="800" alt="Screenshot 2022-05-08 at 5 03 17 PM" src="https://user-images.githubusercontent.com/58494292/167289257-28c1925d-3769-47e6-aa20-2f1c491662b0.png">

**Comment by Moarram** [comment]
Unfortunately it looks like Victor Mono doesn't have a ligature for more than 2 adjacent underscores (rubjo/victor-mono#123).

**Comment by iCraft85** [comment]
Is it possible for me to like add those?

**Comment by Moarram** [comment]
Both of those are probably possible but I don't know anything about it. I'm going to close this for now. Feel free to re-open if you make any progress or have more questions.
