### ISSUE TITLE
Oh My Posh recreation

### ISSUE THREAD

**Issue by wathhr** [Moarram/headline#13]
Hey! I've recreated this theme for [oh-my-posh](https://ohmyposh.dev/), will there be any problems if I keep it published? You can see everything on the [headline-omp repository](https://github.com/wathhr/headline-omp/).

If you have any problems with this, please tell me and I will take care of them!

**Comment by Moarram** [comment]
Looks great! I've added a link in the Headline README

**Comment by wathhr** [comment]
Oh thanks, that's very nice! Really do appreciate it!
