### ISSUE TITLE
Virtual Environment Support

### ISSUE THREAD

**Issue by jdvala** [Moarram/headline#16]
Hi, I really like this theme, but I work mainly with Python and it does not support virtualenvs. Also there is not documentation to add or swap variables.

Could you add an example to add or swap environment variables? 

Thanks

**Comment by Moarram** [comment]
I don't have experience with Python virtualenvs but it looks like they work fine:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/24483562/186756244-4ca8dc45-b825-433e-94f0-e324a93f073d.png">

As for adding or swapping environment variables, you might be looking for the [`env`](https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html) command? The virtualenv docs talk about [environment variables](https://virtualenv.pypa.io/en/latest/cli_interface.html#environment-variables) also.

**Comment by Moarram** [comment]
In case anyone stumbles across this issue, I'd like to mention that after a substantial refactor it's much easier to add/change/remove segments (see [Add Segment](https://github.com/Moarram/headline/blob/main/docs/Customization.md#add-segment)).

And a segment for python `VIRTUAL_ENV` is enabled by default.
