### ISSUE TITLE
Using param expansion to load customization variables from .zshrc

### ISSUE THREAD

**Issue by fabricionaweb** [Moarram/headline#18]
Im using with oh-my-zsh and I just need to change the `.zshrc` file to load the theme.

I notice you have a good amount of customizations variable, but Its all defined directly in the code.

I'd suggest use something like [expansion variables](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion), this way it can read the value or use the defaults

Some other themes use it like here https://github.com/spaceship-prompt/spaceship-prompt/blob/master/spaceship.zsh#L89

Suggestion is
```
HEADLINE_DO_CLOCK="${HEADLINE_DO_CLOCK=false}"
```

When change the value in `.zshrc` itself

```
ZSH_THEME="headline"
HEADLINE_DO_CLOCK="true"
```

**Comment by Moarram** [comment]
This is a great suggestion. It allows variables to be defined before or after sourcing the theme, which reduces confusion and increases robustness.

However, this comes at the expense of making the variable definitions uglier in the code (long variable names twice per line). This probably doesn't matter, but I took great care to make Headline a single stand alone file, and I imagine some people would prefer to edit the variables directly in the theme file. If only Zsh had some sort of conditional assignment operator I could solve for both goals.

You still can set the variables in your `.zshrc`, but you have to do it after you source oh-my-zsh:

```
ZSH_THEME="headline"
source "$HOME/.oh-my-zsh.zsh"
HEADLINE_DO_CLOCK="true"
```

**Comment by fabricionaweb** [comment]
ah thats nice, I did not tried to added it before omz load, thanks.

Yeah, just a suggestion 😊
