### ISSUE TITLE
Error after precmd refactor.

### ISSUE THREAD

**Issue by williamrowell** [Moarram/headline#25]
This just popped up today for me, without any changes to headline configuration.  I suspect my dotfiles manager just pulled the newest version of the theme for the first time in a while (set to pull newest copy in `main` every ~6 months).

```
headline-precmd:26: closing brace expected
```

This is on `zsh 5.8 (x86_64-redhat-linux-gnu)` on Rocky9.2.

No issues on `zsh 5.9 (arm-apple-darwin21.3.0)` on Sonoma 14.7.

**Comment by Moarram** [comment]
I believe I've fixed the issue. Let me know if it works for you now

**Comment by williamrowell** [comment]
Works great for me.  Thanks so much for a quick solution, and for maintaining this nice theme.
