### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TaChao** [Moarram/headline#3]
1. control + l will clear headline output , to solve this:
```
PROMPT='$(precmd_headline)
$ '
```
2. consider use this lib instead of python script?
https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/git.zsh

**Comment by Moarram** [comment]
Good ideas. I'm working on it.

**Comment by Moarram** [comment]
Commit [fff4ef8](https://github.com/Moarram/headline/commit/fff4ef8a5c94d117e9a9cd0e999a32cd13db383f) addresses the Ctrl+L issue

**Comment by Moarram** [comment]
My fix for the Ctrl+L issue causes the prompt to eat previous output when the window is resized, so I am putting this feature behind a flag.

Set `HEADLINE_INFO_MODE=prompt` for Ctrl+L to work , or keep default `HEADLINE_INFO_MODE=precmd` for window resizing to work.

Also there is no longer a Python dependency for Git status
