### ISSUE TITLE
How to set symbols, configure hide/show user and host, and change colors.

### ISSUE THREAD

**Issue by pedrogcamposb** [Moarram/headline#7]
Hey, first of all, congratulations on the theme, it is the best theme I ever found for terminal.

a) I opened this issue because it wasn't clear to me how to set icons, I am using FiraCode as my font, but I don't know how to set the symbols, should I download any? I went to the Nerd Fonts page you linked to, but I didn't understand what should I do from there. Could you explain how to set symbols step-by-step? I really like the symbols you used in your example, it could be those.

b) Is there a way to hide the user and host from the theme, displaying only the path and git?

c) From what I understood, the colors of the theme can be changed using ANSI SGR codes, could you explain how to do it?

Thank you very much for the attention.

**Comment by Moarram** [comment]
I'm glad you like it!

a) FiraCode by itself doesn't have the symbols, you need a font that has them. Here is what I did to set up FiraCode Nerd Font:

1. Follow the link to [FiraCode Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode), navigate to the `ttf` file for the font size you want (such as `Regular > complete > Fira Code Regular Nerd Font Complete.ttf`, and download it (right click should have an option)
1. Add it to your system (probably by double clicking the font file)
1. Set it as the font for your terminal (depends on your terminal, might need to enable font ligatures)
1. Set your desired symbols by assigning to the variables `HEADLINE_USER_PREFIX`, `HEADLINE_HOST_PREFIX`, `HEADLINE_PATH_PREFIX`, and `HEADLINE_BRANCH_PREFIX`. You can do this in your `~/.zshrc` after the theme has been sourced, or in the theme file itself. The symbols I used are in comments in the theme file, but you will only see them properly once your font is installed.

Your next two questions are easily answered by looking in the theme file, which I *highly* recommend.

b) To hide the user and host, set `HEADLINE_DO_USER='false'` and `HEADLINE_DO_HOST='false'`.

c) To change the colors and styles, assign ANSI SGR codes to the style variables. The common codes are already aliased. To make the path italic green for example, you would set `HEADLINE_STYLE_PATH=$italic$green`.

**Comment by pedrogcamposb** [comment]
Thanks! I was able to download the font and find your icons. However, I am still not able to set the icons, nor hide user/host and change the colors... I am attaching a screenshot of my terminal and also a copy of o my .zshrc file. In iTerm, I set the font to FiraCode Nerd Font and ligatures are on. I don't see what could be wrong.

<img width="887" alt="Screen Shot 2021-11-20 at 16 21 16" src="https://user-images.githubusercontent.com/71517464/142738636-331facba-c9b2-472e-8fbe-f3a4ab690596.png">

[zshrc.zsh.zip](https://github.com/Moarram/headline/files/7575111/zshrc.zsh.zip)

**Comment by Moarram** [comment]
The variables need to be set after `headline.zsh-theme` is sourced. You set `ZSH_THEME="headline"`, but Headline it isn't sourced until Oh-My-Zsh reads that variable and acts on it. Try putting the Headline variables somewhere below `source $ZSH/oh-my-zsh.sh`.

**Comment by pedrogcamposb** [comment]
It worked! How silly of me! Sorry, I am this is all new to me, I very much appreciate your help and patience. Keep up the good work!
