### ISSUE TITLE
theme and colors like on screenshot

### ISSUE THREAD

**Issue by gblazex** [Moarram/headline#8]
Hey how can I make my iTerm2 look exactly like your first screenshot (light) theme?
Background and colors too.
https://raw.githubusercontent.com/moarram/headline/assets/images/zsh_theme_light.png

Solarized light doesn't seem to do the trick.

**Comment by gblazex** [comment]
closing this because it's not really an issue just a question, if you have an answer feel free to pop in with the theme you're using

**Comment by gblazex** [comment]
i figured it was the "brighten bold colors" option inside iTerm that messed it up. It's only good for dark themes, and it was messing up light ones.

thanks for the great plugin

**Comment by Moarram** [comment]
Glad you got it working! Here are my [iTerm2 color schemes](https://github.com/Moarram/dotfiles/tree/main/itermcolors) if you still want them.

**Comment by gblazex** [comment]
Omg thank you so much bro!

I’ll  definitely try those!
The brown one looked cool too.

**Comment by iCraft85** [comment]
So I wanted to convert the colorscheme to work for kitty wanted to know wht the hex values of each of those was, not sure how to convert it

**Comment by Moarram** [comment]
**Dark Theme**
```
#212121 Ansi 0
#EE5656 Ansi 1
#84D74B Ansi 2
#EFC83D Ansi 3
#5EAFFF Ansi 4
#EB6AB9 Ansi 5
#5ED7AF Ansi 6
#CCCCCC Ansi 7
#535353 Ansi 8
#FF7B7B Ansi 9
#B7F178 Ansi 10
#FAEF59 Ansi 11
#89DFFF Ansi 12
#FFA3D5 Ansi 13
#95FFE9 Ansi 14
#F4F4F4 Ansi 15
#101010 Background
#E3E3E3 Foreground
#E3E3E3 Cursor
```
<br>

**Light Theme**
```
#252525 Ansi 0
#DB4F4F Ansi 1
#6FAE44 Ansi 2
#E49F26 Ansi 3
#4C8FDD Ansi 4
#CD58DC Ansi 5
#17AA9B Ansi 6
#E4E1DE Ansi 7
#9F9994 Ansi 8
#ED7B7B Ansi 9
#96D262 Ansi 10
#E8C138 Ansi 11
#84B7EA Ansi 12
#F271BF Ansi 13
#63CBA8 Ansi 14
#F9F8F7 Ansi 15
#EFEEEC Background
#323232 Foreground
#8F8C88 Cursor
```
<br>

**Brown Theme**
```
#432C1A Ansi 0
#E34642 Ansi 1
#909B00 Ansi 2
#ECA915 Ansi 3
#4698A3 Ansi 4
#DA698D Ansi 5
#BA7C3E Ansi 6
#DDC165 Ansi 7
#896B4C Ansi 8
#E17662 Ansi 9
#BFC659 Ansi 10
#FFCA1B Ansi 11
#7CC9CF Ansi 12
#F492A6 Ansi 13
#E6A96B Ansi 14
#FFEAA3 Ansi 15
#33200E Background
#F2D886 Foreground
#E4CA77 Cursor
```
