### ISSUE TITLE
Change to `HEADLINE_…_PREFIX='a '` has no effect.

### ISSUE THREAD

**Issue by Mo1802** [Moarram/headline#9]
First of all, thank you for this very great theme. I am a big fan.
I only have one problem with the setup.
I changed `HEADLINE_USER_PREFIX="a "` (and analogously HOST, BRANCH and so on) but I don't see any change in my terminal.
Is there another setting I may need to change that I may have overlooked?
I had no problems with other adjustments.
Thanks already and thanks again for the great theme!
<img width="1278" alt="Bildschirmfoto 2021-12-12 um 02 02 43" src="https://user-images.githubusercontent.com/56798283/145696637-f5bdce86-013a-4eb9-982f-b95fb4677afd.png">

**Comment by Moarram** [comment]
The variable must be set *after* the theme file is sourced or it will be overwritten by the defaults. To test, enter `echo $HEADLINE_USER_PREFIX` at the command line to make sure the variable is set properly. If it's not, try moving the variable assignment towards the end of your `~/.zshrc`.

**Comment by Mo1802** [comment]
Thank you! I got it to work now!
Thank you once more!
